{{- $appName := include "app.name" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" $ | nindent 6 }}
  {{- if not .Values.autoscaling.enabled }}
  {{- with .Values.replicaCount }}
  replicas: {{ . }}
  {{- end }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" $ | nindent 8 }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.dynatrace.enabled }}
        oneagent.dynatrace.com/inject: "{{ .Values.dynatrace.inject | default "true" }}"
        dynatrace.com/instrument: "{{ .Values.dynatrace.instrument | default "false" }}"
        {{- end }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      {{- end }}

      {{- /* FIRST pod-level securityContext (gMSA / podSecurityContext) */}}
      {{- if and .Values.serviceAccount.gmsa.enabled (not .Values.podSecurityContext) }}
      securityContext:
        windowsOptions:
          gmsaCredentialSpecName: {{ include "app.serviceAccountName" . }}
      {{- else if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}

      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range . }}
        - {{- toYaml . | nindent 10 }}
          labelSelector:
            matchLabels:
              {{- include "app.selectorLabels" $ | nindent 14 }}
        {{- end }}
      {{- end }}

      containers:
        - name: {{ $appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- /* EXPLICIT env (including Dynatrace) */}}
          {{- if or .Values.env .Values.dynatrace.env }}
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.dynatrace.enabled }}
            {{- range $name, $value := .Values.dynatrace.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          {{- end }}

          envFrom:
            - configMapRef:
                name: {{ $appName }}
            {{- range .Values.secrets }}
            {{- if eq .type "map" }}
            - secretRef:
                name: {{ printf "%s-%s" $appName ( tpl .nameSuffix $ ) }}
            {{- end }}
            {{- end }}

          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          volumeMounts:
            {{- range .Values.secrets }}
            {{- if eq .type "file" }}
            - name: {{ tpl .nameSuffix $ }}
              mountPath: {{ .mountPath }}
            {{- end }}
            {{- end }}
            {{- range .Values.volumes }}
            - name: {{ .name }}
              mountPath: {{ tpl .mountPath $ }}
            {{- end }}

      volumes:
        {{- range .Values.secrets }}
        {{- if eq .type "file" }}
        - name: {{ tpl .nameSuffix $ }}
          secret:
            secretName: {{ printf "%s-%s" $appName ( tpl .nameSuffix $ ) }}
        {{- end }}
        {{- end }}
        {{- range .Values.volumes }}
        - name: {{ .name }}
          {{- with .hostPath }}
          hostPath:
            {{-  tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .pvc }}
          persistentVolumeClaim:
            claimName: {{ printf "%s-%s" $appName .nameSuffix }}
          {{- end }}
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- /* SECOND pod-level securityContext (kept as your senior recommended) */}}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}